# This workflow deploys a Create React App build to GitHub Pages

name: Deploy to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on pushes to the main branch
  push:
    branches:
      - main # Change this to 'master' if your default branch is master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job handles the build and deployment
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # --- Add this permissions block to grant write access ---
    permissions:
      contents: write # This grants permission to write to the repository content (including pushing branches)

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Recommend using a recent LTS version

      # Install dependencies
      - name: Install dependencies
        run: npm install # Use 'yarn install' if you prefer Yarn

      # Build the React application
      - name: Build application
        run: npm run build # Use 'yarn build' if you prefer Yarn

      # Deploy to GitHub Pages
      # This action automatically handles creating the gh-pages branch and pushing the build output
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically provides this token
          publish_dir: ./build # The directory containing the build output

